[ 2024-10-18 10:14:28,510 ] root - ERROR - An error occured
Traceback (most recent call last):
  File "c:/Users/Admin/Desktop/Major_Project/US-Visaa-MLOPS/demo.py", line 7, in <module>
    a=2/0
ZeroDivisionError: division by zero
